import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

// Couleurs basées sur le tailwind.config.cjs
const colors = {
    primaryBlueStart: '#3A8DFF',
    primaryBlueEnd: '#4FAAFF',
    primaryGreenStart: '#1FC47A',
    primaryGreenEnd: '#27D48B',

    // Ajoutez ces nouvelles couleurs :
    primaryBlueStart40: '#3A8DFF66', // 40% opacity
    primaryBlueEnd40: '#4FAAFF66',
    primaryGreenStart40: '#1FC47A66',
    primaryGreenEnd40: '#27D48B66',

    // Gardez les existants :
    primaryBlueStart20: '#3A8DFF33',
    primaryBlueEnd20: '#4FAAFF33',
    primaryGreenStart20: '#1FC47A33',
    primaryGreenEnd20: '#27D48B33',
    primaryBlueStart5: '#3A8DFF0D',
    primaryGreenEnd5: '#27D48B0D',

    // Couleurs neutres
    white: '#FFFFFF',
    gray700: '#374151',
    gray600: '#4B5563',
    gray500: '#6B7280',
    gray400: '#9CA3AF',
    gray300: '#D1D5DB',
    gray200: '#E5E7EB',
    gray100: '#F3F4F6',
    gray50: '#F9FAFB',
};
// ========================== STYLES ==========================
export const styles = StyleSheet.create({
    // Conteneurs principaux
    container: {
        flex: 1,
        backgroundColor: colors.white,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.white,
    },
    loadingText: {
        fontSize: 18,
        color: colors.primaryBlueStart,
    },
    gradientBackground: {
        flex: 1,
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 20,
    },
    logoMask: {
        fontSize: 32,
        fontWeight: 'bold',
        letterSpacing: 1,
        textAlign: 'left',
    },

    // Header avec dégradé
    headerContainer: {
        borderBottomLeftRadius: 25,
        borderBottomRightRadius: 25,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.15,
        shadowRadius: 15,
        elevation: 10,
        marginBottom: 5,
    },
    gradientHeader: {
        paddingTop: 45,
        paddingBottom: 15,
        paddingHorizontal: 16,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    logoContainer: {
        flex: 1,
        alignItems: 'center',
    },
    logo: {
        fontSize: 32,
        fontWeight: 'bold',
        color: colors.white,
        textShadowColor: 'rgba(0, 0, 0, 0.25)',
        textShadowOffset: { width: 1, height: 2 },
        textShadowRadius: 4,
        marginBottom: 6,
        letterSpacing: 0.5,
    },
    tagline: {
        fontSize: 15,
        color: 'rgba(255, 255, 255, 0.95)',
        fontWeight: '500',
        letterSpacing: 0.3,
    },
    menuButton: {
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },

    // Menu hamburger
    menuOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0)',
    },
    menuContent: {
        width: width * 0.95,
        backgroundColor: colors.white,
        height: '100%',
        alignSelf: 'flex-end',
    },
    menuHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 25,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray200,
    },
    menuLogoContainer: {
        flex: 1,
    },
    menuLogo: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.gray700,
    },
    menuTagline: {
        fontSize: 14,
        color: colors.primaryBlueStart,
        marginTop: 4,
    },
    closeButton: {
        padding: 8,
    },
    menuItems: {
        flex: 1,
        paddingVertical: 10,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray50,
    },
    menuIcon: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 15,
    },
    menuTextContainer: {
        flex: 1,
    },
    menuItemTitle: {
        fontSize: 20,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 2,
    },
    menuItemSubtitle: {
        fontSize: 13,
        color: colors.gray500,
    },
    menuFooter: {
        padding: 25,
        borderTopWidth: 1,
        borderTopColor: colors.gray200,
        alignItems: 'center',
    },
    menuFooterText: {
        fontSize: 14,
        color: colors.primaryBlueStart,
        marginBottom: 4,
    },
    menuFooterCopyright: {
        fontSize: 12,
        color: colors.gray400,
    },

    // Hero Section
    heroSection: {
        height: height * 0.42,
        marginHorizontal: 16,
        borderRadius: 22,
        overflow: 'hidden',
        marginTop: 10,
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 12,
        elevation: 10,
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },

    heroImage: {
        width: '100%',
        height: '100%',
    },
    heroOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingVertical: 28,
        paddingHorizontal: 22,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },

    heroTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.white,
        textAlign: 'center',
        lineHeight: 26,
        letterSpacing: 0.3,
    },

    // Sections communes
    section: {
        paddingHorizontal: 20,
        marginBottom: 25,
    },
    description: {
        fontSize: 17,
        color: colors.gray600,
        textAlign: 'center',
        lineHeight: 24,
    },
    sectionTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.gray700,
        textAlign: 'center',
        marginBottom: 20,
    },

    // Benefits
    benefitsSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        marginBottom: 30,
    },
    benefitCard: {
        flex: 1,
        alignItems: 'center',
        paddingHorizontal: 10,
        backgroundColor: colors.white,
        borderRadius: 12,
        padding: 15,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        marginHorizontal: 5,
    },
    benefitIcon: {
        width: 70,
        height: 70,
        borderRadius: 35,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    benefitTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 5,
        textAlign: 'center',
    },
    benefitText: {
        fontSize: 13,
        color: colors.gray500,
        textAlign: 'center',
        lineHeight: 18,
    },

    // Statistics
    statsSection: {
        flexDirection: 'row',
        backgroundColor: colors.white,
        marginHorizontal: 20,
        borderRadius: 18,
        paddingVertical: 25,
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    statCard: {
        flex: 1,
        alignItems: 'center',
    },
    statNumber: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.primaryGreenStart,
        marginBottom: 6,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statLabel: {
        fontSize: 13,
        color: colors.gray500,
        textAlign: 'center',
        paddingHorizontal: 5,
    },

    // Role Selection
    roleSection: {
        paddingHorizontal: 20,
        marginBottom: 30,
    },
    roleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 18,
        padding: 22,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    passengerButton: {
        // Le background sera géré par LinearGradient
    },
    driverButton: {
        // Le background sera géré par LinearGradient
    },
    roleIconContainer: {
        width: 54,
        height: 54,
        borderRadius: 27,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 18,
    },
    roleTextContainer: {
        flex: 1,
    },
    roleTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.white,
        marginBottom: 4,
    },
    roleSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
    },

    // Testimonials
    testimonialsSection: {
        paddingHorizontal: 20,
        marginBottom: 30,
    },
    testimonialCard: {
        backgroundColor: colors.white,
        borderRadius: 18,
        padding: 22,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    testimonialHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 14,
    },
    ratingStars: {
        flexDirection: 'row',
    },
    testimonialDate: {
        fontSize: 13,
        color: colors.gray400,
    },
    testimonialText: {
        fontSize: 16,
        color: colors.gray600,
        lineHeight: 24,
        marginBottom: 14,
    },
    testimonialAuthor: {
        fontSize: 15,
        fontWeight: '600',
        color: colors.gray700,
    },

    // Download Section
    downloadSection: {
        backgroundColor: colors.white,
        paddingVertical: 35,
        paddingHorizontal: 20,
        marginBottom: 30,
        borderRadius: 18,
        marginHorizontal: 20,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    downloadText: {
        fontSize: 16,
        color: colors.gray600,
        textAlign: 'center',
        marginBottom: 25,
    },
    downloadButtons: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 15,
    },
    downloadButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 14,
        paddingVertical: 16,
        paddingHorizontal: 18,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
        minHeight: 80,
        maxWidth: 170,
    },
    downloadIcon: {
        marginRight: 12,
    },
    downloadButtonText: {
        flex: 1,
    },
    downloadSmall: {
        fontSize: 12,
        color: colors.gray500,
        marginBottom: 4,
    },
    downloadLarge: {
        fontSize: 15,
        fontWeight: 'bold',
        color: colors.gray700,
    },

    // Contact Form
    contactSection: {
        paddingHorizontal: 20,
        marginBottom: 30,
    },
    contactText: {
        fontSize: 16,
        color: colors.gray500,
        textAlign: 'center',
        marginBottom: 25,
    },
    form: {
        marginBottom: 25,
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 10,
    },
    textInput: {
        backgroundColor: colors.white,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 14,
        fontSize: 16,
        color: colors.gray700,
    },
    textArea: {
        height: 130,
        paddingTop: 18,
    },
    submitButton: {
        backgroundColor: colors.primaryGreenStart,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 18,
        borderRadius: 14,
        marginTop: 10,
        shadowColor: colors.primaryGreenStart,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    submitButtonText: {
        color: colors.white,
        fontSize: 17,
        fontWeight: 'bold',
        marginRight: 12,
    },
    submitButtonGradient: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 16,
        borderRadius: 30,
        marginTop: 10,
        gap: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 6,
    },
    quickContact: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginTop: 15,
        paddingHorizontal: '10',
    },
    contactItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    contactDetail: {
        fontSize: 15,
        color: colors.gray600,
        marginLeft: 10,
    },

    // Footer
    footer: {
        backgroundColor: colors.gray700,
        paddingVertical: 35,
        alignItems: 'center',
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
    },
    footerLogo: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.white,
        marginBottom: 12,
    },
    footerCopyright: {
        fontSize: 14,
        color: colors.gray400,
        marginBottom: 20,
    },
    footerLinks: {
        flexDirection: 'row',
        gap: 25,
    },
    footerLink: {
        fontSize: 14,
        color: colors.gray300,
    },

    // Styles pour le menu pro
    overlayTouchable: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    menuLogoGradient: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
        shadowColor: colors.primaryBlueStart,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    badge: {
        backgroundColor: '#F59E0B',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 10,
        marginLeft: 10,
    },
    badgeText: {
        color: colors.white,
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    closeButtonGradient: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.2)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
    },
    profileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255, 255, 255, 0.1)',
        marginBottom: 10,
    },
    profileAvatar: {
        marginRight: 15,
    },
    profileGradient: {
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#6366F1',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    profileInfo: {
        flex: 1,
    },
    profileName: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.white,
        marginBottom: 4,
    },
    profileStatus: {
        fontSize: 13,
        color: '#94A3B8',
    },
    profileArrow: {
        padding: 8,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 10,
    },
    menuItemPro: {
        borderRadius: 16,
        overflow: 'hidden',
        marginHorizontal: 15,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 3,
    },
    menuItemGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 18,
        borderRadius: 16,
    },
    menuIconPro: {
        marginRight: 15,
    },
    menuIconBackground: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    menuItemTitlePro: {
        fontSize: 15,
        fontWeight: '600',
        color: colors.white,
        marginBottom: 4,
    },
    menuItemSubtitlePro: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.7)',
    },
    menuArrowPro: {
        marginLeft: 'auto',
    },
    menuFooterPro: {
        paddingHorizontal: 20,
        paddingVertical: 20,
        borderTopWidth: 1,
        borderTopColor: 'rgba(255, 255, 255, 0.1)',
    },
    footerContent: {
        alignItems: 'center',
    },
    versionInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: 'rgba(16, 185, 129, 0.2)',
    },
    versionText: {
        fontSize: 11,
        color: colors.primaryGreenStart,
        fontWeight: '600',
        marginLeft: 8,
        letterSpacing: 0.3,
    },
    copyrightText: {
        fontSize: 11,
        color: '#64748B',
        textAlign: 'center',
        letterSpacing: 0.2,
    },
    glowEffect: {
        position: 'absolute',
        left: -15,
        top: 0,
        bottom: 0,
        width: 15,
        backgroundColor: 'rgba(56, 189, 248, 0.15)',
        shadowColor: colors.primaryBlueStart,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.4,
        shadowRadius: 20,
        elevation: 5,
    },

    // ==================== MODAL CHOIX DE PROFIL ====================
    profileChoiceOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    profileChoiceModal: {
        backgroundColor: colors.white,
        borderRadius: 20,
        width: '100%',
        maxWidth: 350,
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 20,
        elevation: 10,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    profileChoiceHeader: {
        marginBottom: 24,
        alignItems: 'center',
    },
    profileChoiceTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.gray700,
        marginBottom: 8,
        textAlign: 'center',
    },
    profileChoiceSubtitle: {
        fontSize: 14,
        color: colors.gray500,
        textAlign: 'center',
        lineHeight: 20,
    },
    profileChoiceCards: {
        flexDirection: 'column',
        gap: 16,
        marginBottom: 20,
    },
    profileChoiceCard: {
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 4,
    },
    profileChoiceIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 16,
    },
    chauffeurIcon: {
        backgroundColor: '#FEF3C7',
    },
    profileChoiceCardTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 8,
    },
    profileChoiceCardDescription: {
        fontSize: 14,
        color: colors.gray500,
        lineHeight: 20,
        marginBottom: 20,
    },
    profileChoiceButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: colors.gray50,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    chauffeurButton: {
        backgroundColor: '#FEF3C7',
        borderColor: '#FDE68A',
    },
    profileChoiceButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.primaryBlueStart,
        marginRight: 8,
    },
    profileChoiceCancel: {
        paddingVertical: 14,
        alignItems: 'center',
        borderRadius: 12,
        backgroundColor: colors.gray50,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    profileChoiceCancelText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray600,
    },

    // ==================== STYLES POUR LA PAGE FONCTIONNALITÉS ====================
    featuresHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray200,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.gray100,
        justifyContent: 'center',
        alignItems: 'center',
    },
    featuresTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.gray700,
    },
    featuresScroll: {
        flex: 1,
        backgroundColor: colors.gray50,
    },
    heroSectionFeatures: {
        padding: 24,
        backgroundColor: colors.primaryBlueStart,
        alignItems: 'center',
    },
    heroTitleFeatures: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.white,
        textAlign: 'center',
        marginBottom: 8,
    },
    heroSubtitleFeatures: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        textAlign: 'center',
        lineHeight: 22,
    },
    sectionContainer: {
        padding: 20,
    },
    sectionTitleFeatures: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.gray700,
        marginBottom: 8,
    },
    sectionDescription: {
        fontSize: 16,
        color: colors.gray500,
        marginBottom: 20,
    },
    featuresGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    featureCard: {
        width: width * 0.9 - 40,
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    featureIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    featureCardTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 8,
    },
    featureCardDescription: {
        fontSize: 14,
        color: colors.gray500,
        lineHeight: 20,
        marginBottom: 12,
    },
    featureDetails: {
        marginTop: 8,
    },
    detailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    detailText: {
        fontSize: 12,
        color: colors.gray500,
        marginLeft: 6,
        flex: 1,
    },
    avantagesContainer: {
        marginTop: 10,
    },
    avantageCard: {
        backgroundColor: colors.white,
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        flexDirection: 'row',
        alignItems: 'flex-start',
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    avantageIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#F5F3FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    avantageTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 4,
    },
    avantageDescription: {
        fontSize: 14,
        color: colors.gray500,
        lineHeight: 20,
        flex: 1,
    },
    ctaContainer: {
        padding: 24,
        backgroundColor: colors.primaryBlueStart,
        margin: 20,
        borderRadius: 20,
        alignItems: 'center',
    },
    ctaTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: colors.white,
        marginBottom: 8,
        textAlign: 'center',
    },
    ctaDescription: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 22,
    },
    ctaButton: {
        backgroundColor: colors.white,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 12,
        marginBottom: 12,
        width: '100%',
    },
    ctaButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.primaryBlueStart,
        marginLeft: 8,
    },
    secondaryButton: {
        paddingVertical: 12,
    },
    secondaryButtonText: {
        fontSize: 14,
        color: colors.white,
        textDecorationLine: 'underline',
    },
    // Styles spécifiques pour Contact
    contactFormContainer: {
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: 24,
        marginHorizontal: 20,
        marginTop: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    contactMethodCard: {
        width: (width - 88) / 2,
        backgroundColor: colors.gray50,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    contactIconContainer: {
        width: 48,
        height: 48,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    contactMethodTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 8,
    },
    contactMethodDetail: {
        fontSize: 14,
        color: colors.gray500,
        lineHeight: 20,
        marginBottom: 4,
    },
    faqItem: {
        backgroundColor: colors.gray50,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        marginBottom: 16,
        padding: 16,
        borderRadius: 12,
    },
    faqQuestion: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 8,
    },
    faqAnswer: {
        fontSize: 14,
        color: colors.gray500,
        lineHeight: 20,
    },

    // ==================== STYLES PAGER PASSAGER ====================
    passagerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray200,
    },
    passagerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.gray700,
    },
    profileButton: {
        padding: 4,
    },

    // Carte
    mapContainer: {
        height: height * 0.6,
        position: 'relative',
    },
    map: {
        width: '100%',
        height: '100%',
    },
    loadingMap: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.gray50,
    },
    mapError: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.gray50,
    },
    mapErrorText: {
        marginTop: 12,
        fontSize: 16,
        color: colors.gray500,
    },
    retryButton: {
        marginTop: 20,
        paddingVertical: 10,
        paddingHorizontal: 20,
        backgroundColor: colors.primaryBlueStart,
        borderRadius: 8,
    },
    retryButtonText: {
        color: colors.white,
        fontWeight: '600',
    },

    // Marqueurs
    userMarker: {
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: 6,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    driverMarker: {
        backgroundColor: colors.primaryGreenStart,
        borderRadius: 15,
        padding: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    selectedDriverMarker: {
        backgroundColor: colors.primaryBlueStart,
        transform: [{ scale: 1.2 }],
    },

    // Overlay de recherche
    searchOverlay: {
        position: 'absolute',
        top: 20,
        left: 20,
        right: 20,
        zIndex: 10,
    },
    searchCard: {
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    searchTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.gray700,
        marginBottom: 16,
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    inputIcon: {
        marginRight: 12,
    },
    inputContent: {
        flex: 1,
    },
    inputLabel: {
        fontSize: 12,
        color: colors.gray500,
        marginBottom: 4,
    },
    input: {
        fontSize: 16,
        color: colors.gray700,
        padding: 0,
    },
    currentLocationButton: {
        padding: 8,
        backgroundColor: colors.gray100,
        borderRadius: 8,
    },
    separatorLine: {
        height: 1,
        backgroundColor: colors.gray200,
        marginVertical: 12,
        marginLeft: 32,
    },
    suggestionsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 12,
        marginBottom: 16,
    },
    suggestionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.gray50,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        marginRight: 8,
        marginBottom: 8,
    },
    suggestionText: {
        fontSize: 12,
        color: colors.gray500,
        marginLeft: 4,
    },
    searchButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primaryBlueStart,
        paddingVertical: 16,
        borderRadius: 12,
        gap: 10,
    },
    searchButtonDisabled: {
        backgroundColor: colors.gray400,
    },
    searchButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: '600',
    },

    // Résultats
    resultsContainer: {
        paddingHorizontal: 20,
        paddingTop: 20,
    },
    resultsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    resultsTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: colors.gray700,
    },
    tripDetailsCard: {
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 20,
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
    },
    tripDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    detailItem: {
        alignItems: 'center',
        flex: 1,
    },
    detailLabel: {
        fontSize: 12,
        color: colors.gray500,
        marginTop: 8,
        marginBottom: 4,
    },
    detailValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.gray700,
    },
    tripSeparator: {
        height: 1,
        backgroundColor: colors.gray200,
        marginVertical: 16,
    },
    routeContainer: {
        marginTop: 8,
    },
    routePoint: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    routeDotStart: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: colors.primaryGreenStart,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    routeDotEnd: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#EF4444',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    routeLine: {
        position: 'absolute',
        left: 11,
        top: 24,
        bottom: -20,
        width: 2,
        backgroundColor: colors.gray300,
    },
    routeTextContainer: {
        flex: 1,
    },
    routeTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 2,
    },
    routeAddress: {
        fontSize: 14,
        color: colors.gray500,
        lineHeight: 20,
    },

    // Chauffeurs
    driversTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.gray700,
        marginBottom: 16,
    },
    driversScroll: {
        marginBottom: 24,
    },
    driverCard: {
        width: 200,
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 16,
        marginRight: 16,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    selectedDriverCard: {
        borderColor: colors.primaryBlueStart,
        borderWidth: 2,
        backgroundColor: '#F0F9FF',
    },
    driverHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    driverAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primaryBlueStart,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    driverInitial: {
        color: colors.white,
        fontSize: 18,
        fontWeight: 'bold',
    },
    driverInfo: {
        flex: 1,
    },
    driverName: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 4,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    driverRating: {
        fontSize: 14,
        color: colors.gray500,
        marginLeft: 4,
    },
    driverDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray200,
    },
    carInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    carText: {
        fontSize: 14,
        color: colors.gray500,
        marginLeft: 6,
    },
    carPlate: {
        fontSize: 12,
        color: colors.gray700,
        fontWeight: '600',
        backgroundColor: colors.gray100,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    driverFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    distanceInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    distanceText: {
        fontSize: 14,
        color: colors.gray500,
        marginLeft: 4,
    },
    etaText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.gray700,
    },
    bookButton: {
        backgroundColor: colors.primaryGreenStart,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    bookButtonText: {
        color: colors.white,
        fontSize: 14,
        fontWeight: '600',
    },

    // Options rapides
    quickOptions: {
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 20,
    },
    quickOptionsTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.gray700,
        marginBottom: 16,
    },
    quickOptionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    quickOption: {
        width: (width - 60) / 3,
        alignItems: 'center',
        marginBottom: 20,
    },
    quickOptionIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    quickOptionLabel: {
        fontSize: 12,
        color: colors.gray500,
        textAlign: 'center',
    },

    // Navigation inférieure
    bottomNavigation: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 12,
        backgroundColor: colors.white,
        borderTopWidth: 1,
        borderTopColor: colors.gray200,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 5,
    },
    navItem: {
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    navItemActive: {
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    navActiveIcon: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.primaryBlueStart,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: -20,
        shadowColor: colors.primaryBlueStart,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
    },
    navText: {
        fontSize: 10,
        color: colors.gray500,
        marginTop: 4,
    },
    navActiveText: {
        fontSize: 10,
        color: colors.primaryBlueStart,
        fontWeight: '600',
        marginTop: 4,
    },

    // Styles pour écran de chargement amélioré
    loadingGradient: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
    },
    loadingSpinner: {
        marginTop: 20,
        animation: 'spin 1s linear infinite',
    },

    // Styles pour indicateurs de diapositive
    sliderIndicators: {
        position: 'absolute',
        bottom: 20,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2,
    },
    sliderIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.5)',
        marginHorizontal: 4,
    },
    sliderIndicatorActive: {
        width: 24,
        backgroundColor: colors.white,
    },

    // Styles pour contenu hero amélioré
    heroContent: {
        paddingHorizontal: 20,
    },
    heroSubtitle: {
        fontSize: 18,
        color: 'rgba(255, 255, 255, 0.9)',
        textAlign: 'center',
        marginTop: 8,
        fontWeight: '400',
    },

    // Styles pour section auth (remplace download)
    authSection: {
        backgroundColor: colors.white,
        paddingVertical: 35,
        paddingHorizontal: 20,
        marginBottom: 30,
        borderRadius: 20,
        marginHorizontal: 16,
        borderWidth: 1.5,
        borderColor: colors.primaryBlueStart40,
    },
    authSubtitle: {
        fontSize: 16,
        color: colors.gray600,
        textAlign: 'center',
        marginBottom: 30,
    },
    authButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 15,
    },
    authButton: {
        flex: 1,
        borderRadius: 15,
        overflow: 'hidden',
        minHeight: 70,
    },
    authButtonGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
        gap: 10,
    },
    authButtonContent: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
        borderRadius: 15,
        gap: 10,
    },
    authButtonText: {
        fontSize: 17,
        fontWeight: 'bold',
        color: colors.white,
    },
    signupButton: {
        shadowColor: colors.primaryGreenStart,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    loginButton: {
        shadowColor: colors.primaryBlueStart,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },

    // Styles pour contact amélioré
    contactIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
        borderWidth: 1,
        backgroundColor: colors.primaryBlueStart20,
        borderColor: colors.primaryBlueStart40,
    },

    // Styles pour animation d'entrée
    fadeIn: {
        opacity: 0,
        transform: [{ translateY: 20 }],
    },

    // Styles pour wrapper bouton rôle
    roleButtonWrapper: {
        marginBottom: 16,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
    },

    // Styles pour texte amélioré
    textBold: {
        fontWeight: '700',
    },
    textSemiBold: {
        fontWeight: '600',
    },
    textMedium: {
        fontWeight: '500',
    },

    // Responsive adjustments
    responsivePadding: {
        paddingHorizontal: width > 400 ? 24 : 16,
    },

    // Styles pour le logo avec dégradé (nouveaux)
    logoGradient: {
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    logoText: {
        fontSize: 25,
        fontWeight: '900',
        color: 'white',
        textShadowColor: 'rgba(0, 0, 0, 0.4)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
        letterSpacing: 1,
        lineHeight: 24,
    },
    tagline: {
        fontSize: 11,
        color: 'white',
        marginTop: 6,
        fontWeight: '600',
        textShadowColor: 'rgba(0, 0, 0, 0.2)',
        textShadowOffset: { width: 0.5, height: 0.5 },
        textShadowRadius: 2,
        letterSpacing: 0.5,
    },
    menuButton: {
        padding: 12,
        borderRadius: 12,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },

    // Styles spécifiques pour les sections de l'écran d'accueil
    benefitsSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        marginBottom: 30,
        flexWrap: 'wrap',
    },
    benefitCard: {
        width: '30%',
        minWidth: 100,
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 15,
        marginBottom: 10,
        borderWidth: 1.5,
        borderColor: colors.primaryBlueStart20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 3,
    },
    benefitIcon: {
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        backgroundColor: colors.primaryBlueStart20,
    },
    benefitTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.gray700,
        marginBottom: 4,
        textAlign: 'center',
    },
    benefitText: {
        fontSize: 12,
        color: colors.gray500,
        textAlign: 'center',
        lineHeight: 16,
    },

    // Stats Section ajustée
    statsSection: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        backgroundColor: colors.white,
        marginHorizontal: 16,
        borderRadius: 20,
        paddingVertical: 20,
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1.5,
        borderColor: colors.primaryBlueStart40,
    },
    statCard: {
        width: '50%',
        alignItems: 'center',
        marginBottom: 15,
    },
    statNumber: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.primaryGreenStart,
        marginBottom: 4,
    },

    // Role Section ajustée
    roleSection: {
        paddingHorizontal: 16,
        marginBottom: 30,
    },
    roleButtonWrapper: {
        marginBottom: 16,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 8,
    },
    roleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 20,
        padding: 22,
        marginBottom: 0,
    },
    roleIconContainer: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    roleTextContainer: {
        flex: 1,
    },
    roleTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.white,
        marginBottom: 4,
        letterSpacing: 0.5,
    },
    roleSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        opacity: 0.9,
    },

    // Auth Section ajustée
    authSection: {
        backgroundColor: colors.white,
        paddingVertical: 30,
        paddingHorizontal: 20,
        marginBottom: 30,
        borderRadius: 20,
        marginHorizontal: 16,
        borderWidth: 1.5,
        borderColor: colors.primaryBlueStart40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
    },
    authSubtitle: {
        fontSize: 16,
        color: colors.gray600,
        textAlign: 'center',
        marginBottom: 25,
        lineHeight: 22,
    },
    authButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
    },
    authButton: {
        flex: 1,
        borderRadius: 16,
        overflow: 'hidden',
        minHeight: 65,
    },
    authButtonGradient: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        gap: 10,
    },
    authButtonContent: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 16,
        borderRadius: 16,
        gap: 10,
        backgroundColor: colors.white,
        borderWidth: 2,
        borderColor: colors.primaryBlueStart,
    },
    authButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: colors.white,
    },

    // Contact Section ajustée
    contactSection: {
        paddingHorizontal: 16,
        marginBottom: 30,
    },
    contactText: {
        fontSize: 16,
        color: colors.gray600,
        textAlign: 'center',
        marginBottom: 25,
        lineHeight: 22,
    },
    contactIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: colors.primaryBlueStart20,
        borderWidth: 1,
        borderColor: colors.primaryBlueStart40,
    },
    contactDetail: {
        fontSize: 15,
        color: colors.gray700,
        fontWeight: '500',
    },

    // Testimonials ajustés
    testimonialsSection: {
        paddingHorizontal: 16,
        marginBottom: 30,
    },
    testimonialCard: {
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: 22,
        marginBottom: 16,
        borderWidth: 1.5,
        borderColor: colors.primaryBlueStart20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 4,
    },

    // Form ajusté
    form: {
        marginBottom: 25,
        backgroundColor: colors.white,
        padding: 20,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: colors.primaryBlueStart20,
    },

    // Styles pour le scroll amélioré
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 30,
    },

    // Hero Section ajustée
    heroSection: {
        height: height * 0.45,
        marginHorizontal: 16,
        borderRadius: 24,
        overflow: 'hidden',
        marginTop: 10,
        marginBottom: 30,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 10,
        backgroundColor: colors.white,
        borderWidth: 2,
        borderColor: colors.primaryBlueStart40,
    },
    heroImage: {
        width: '100%',
        height: '100%',
    },
    heroOverlay: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'flex-end',
        paddingBottom: 30,
        paddingHorizontal: 20,
        backgroundColor: 'rgba(0,0,0,0.4)',
    },
    heroContent: {
        alignItems: 'center',
    },
    heroTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.white,
        textAlign: 'center',
        lineHeight: 30,
        marginBottom: 8,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 4,
    },
    heroSubtitle: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.95)',
        textAlign: 'center',
        lineHeight: 22,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
});