import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC',
    },
    contentContainer: {
        flex: 1,
    },

    // Modal styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },

    // Notifications Modal
    notificationsModalContainer: {
        width: width * 0.9,
        height: height * 0.7,
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        overflow: 'hidden',
    },
    notificationsModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
    },
    notificationsModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    closeButton: {
        padding: 4,
    },
    notificationsList: {
        flex: 1,
    },
    notificationItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
        backgroundColor: '#FFFFFF',
    },
    notificationItemUnread: {
        backgroundColor: '#EFF6FF',
    },
    notificationIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    notificationContent: {
        flex: 1,
    },
    notificationTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    notificationMessage: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 4,
    },
    notificationTime: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    unreadDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#3B82F6',
    },
    notificationsModalFooter: {
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
    },

    // Performance Analytics Styles
    performanceCard: {
        marginHorizontal: 16,
        marginTop: 16,
        padding: 20,
        borderRadius: 20,
        borderWidth: 1,
    },
    performanceTitle: {
        fontSize: 18,
        fontWeight: '800',
        marginBottom: 15,
    },
    performanceGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    performanceItem: {
        width: '47%',
        padding: 12,
        borderRadius: 16,
        borderWidth: 1,
    },
    performanceLabel: {
        fontSize: 12,
        fontWeight: '600',
        marginBottom: 8,
    },
    progressContainer: {
        height: 8,
        borderRadius: 4,
        width: '100%',
        backgroundColor: 'rgba(0,0,0,0.05)',
        overflow: 'hidden',
        marginBottom: 6,
    },
    progressBar: {
        height: '100%',
        borderRadius: 4,
    },
    performanceValue: {
        fontSize: 16,
        fontWeight: '800',
    },
    markAllAsReadButton: {
        paddingVertical: 12,
        alignItems: 'center',
    },
    markAllAsReadText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3B82F6',
    },

    // Ride Accept Modal
    rideAcceptModalContainer: {
        width: width * 0.9,
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        overflow: 'hidden',
    },
    rideAcceptModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        backgroundColor: '#F9FAFB',
    },
    rideAcceptModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    rideAcceptContent: {
        padding: 20,
    },
    rideAcceptPassenger: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    rideAcceptAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#3B82F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    rideAcceptInitial: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    rideAcceptName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    rideAcceptRating: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rideAcceptRatingText: {
        fontSize: 16,
        color: '#6B7280',
        marginLeft: 4,
    },
    rideAcceptInfo: {
        marginBottom: 20,
    },
    rideAcceptRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    rideAcceptLocation: {
        flex: 1,
        marginLeft: 12,
    },
    rideAcceptLabel: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 4,
    },
    rideAcceptValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
    },
    rideAcceptMeta: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    rideAcceptMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rideAcceptMetaText: {
        fontSize: 14,
        color: '#6B7280',
        marginLeft: 4,
    },
    rideAcceptPrice: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 20,
        backgroundColor: '#F0FDF4',
        borderRadius: 12,
    },
    rideAcceptPriceLabel: {
        fontSize: 18,
        fontWeight: '600',
        color: '#065F46',
    },
    rideAcceptPriceValue: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#065F46',
    },
    rideAcceptActions: {
        flexDirection: 'row',
        padding: 20,
        gap: 12,
    },
    rejectRideButton: {
        flex: 1,
        paddingVertical: 16,
        backgroundColor: '#FEF2F2',
        borderRadius: 12,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FECACA',
    },
    rejectRideButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#DC2626',
    },
    acceptRideButton: {
        flex: 1,
    },
    acceptRideButtonGradient: {
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    acceptRideButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },

    // ... (Tous les autres styles restent inchangés, ajoutez les nouveaux styles ci-dessus)

    headerGradient: {
        paddingTop: Platform.OS === 'ios' ? 10 : 20,
        paddingBottom: 20,
        paddingHorizontal: 16,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    profileButton: {
        marginRight: 12,
    },
    profileImage: {
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    profileImageReal: {
        width: 50,
        height: 50,
        borderRadius: 25,
        borderWidth: 2,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    profileInitial: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1E40AF',
    },
    headerInfo: {
        flex: 1,
    },
    welcomeText: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.9)',
        marginBottom: 2,
    },
    driverName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    ratingText: {
        fontSize: 14,
        color: '#FFFFFF',
        marginLeft: 4,
        marginRight: 8,
    },
    carInfo: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    headerRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    notificationButton: {
        marginRight: 16,
        position: 'relative',
    },
    notificationBadge: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: '#EF4444',
        borderRadius: 10,
        width: 20,
        height: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: '#FFFFFF',
        fontSize: 10,
        fontWeight: 'bold',
    },
    badgeContainer: {
        backgroundColor: '#3B82F6',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
    },
    settingsButton: {
        padding: 4,
    },

    // Tab content styling
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 100,
    },
    tabContent: {
        paddingBottom: 100,
    },
    subTabContent: {
        paddingBottom: 100,
    },

    // Home Tab Styles
    statusCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    statusHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    statusTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    statusIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 6,
    },
    statusDotOnline: {
        backgroundColor: '#10B981',
    },
    statusDotOffline: {
        backgroundColor: '#6B7280',
    },
    statusText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#6B7280',
    },
    statusContent: {
        marginTop: 8,
    },
    toggleContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    toggleLabel: {
        fontSize: 16,
        color: '#1F2937',
        fontWeight: '500',
    },
    availabilityInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F0FDF4',
        padding: 12,
        borderRadius: 12,
        marginTop: 8,
    },
    availabilityText: {
        fontSize: 14,
        color: '#065F46',
        marginLeft: 8,
    },
    activeRideStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EFF6FF',
        padding: 12,
        borderRadius: 12,
        marginTop: 8,
    },
    activeRideText: {
        fontSize: 14,
        color: '#1E40AF',
        marginLeft: 8,
    },
    earningsCard: {
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
        elevation: 5,
    },
    earningsHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    earningsTitle: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
    },
    viewAllText: {
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: '500',
        textDecorationLine: 'underline',
    },
    earningsAmount: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 20,
    },
    earningsStats: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    statDivider: {
        width: 1,
        height: 30,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    mapSection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 12,
    },
    mapContainer: {
        height: 400,
        borderRadius: 16,
        overflow: 'hidden',
        position: 'relative',
    },
    map: {
        width: '100%',
        height: '100%',
    },
    mapPlaceholder: {
        width: '100%',
        height: '100%',
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
    },
    mapLoadingText: {
        marginTop: 8,
        color: '#6B7280',
    },
    enableLocationButton: {
        marginTop: 12,
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#3B82F6',
        borderRadius: 8,
    },
    enableLocationText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    driverMarker: {
        backgroundColor: '#FFFFFF',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#3B82F6',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    pickupMarker: {
        backgroundColor: '#FFFFFF',
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#10B981',
    },
    destinationMarker: {
        backgroundColor: '#FFFFFF',
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#EF4444',
    },
    mapControls: {
        position: 'absolute',
        top: 12,
        right: 12,
        flexDirection: 'column',
        gap: 8,
    },
    mapControlButton: {
        backgroundColor: '#FFFFFF',
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    currentRideSection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    helpText: {
        fontSize: 14,
        color: '#3B82F6',
        fontWeight: '500',
    },
    currentRideCard: {
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    rideHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    passengerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    passengerAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#3B82F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    passengerInitial: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    passengerName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    passengerRating: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rideStatusBadge: {
        backgroundColor: '#EFF6FF',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    statusBadgeText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#3B82F6',
    },
    rideDetails: {
        marginBottom: 20,
    },
    rideDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    rideDetailText: {
        fontSize: 14,
        color: '#4B5563',
        marginLeft: 8,
        flex: 1,
    },
    rideMeta: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    metaItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    metaText: {
        fontSize: 13,
        color: '#6B7280',
        marginLeft: 4,
    },
    rideActions: {
        flexDirection: 'row',
        gap: 12,
    },
    startRideButton: {
        flex: 1,
    },
    startRideButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
    },
    startRideButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginLeft: 8,
    },
    completeRideButton: {
        flex: 1,
    },
    completeRideButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
    },
    completeRideButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginLeft: 8,
    },
    secondaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#EFF6FF',
        borderRadius: 12,
        paddingVertical: 14,
        paddingHorizontal: 20,
        minWidth: 80,
    },
    secondaryButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#3B82F6',
        marginLeft: 6,
    },
    availableRidesSection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    ridesCount: {
        fontSize: 14,
        color: '#6B7280',
    },
    ridesScrollContent: {
        paddingRight: 16,
    },
    availableRideCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginRight: 12,
        width: width * 0.75,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    availableRideHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    availablePassengerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    availablePassengerAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 8,
    },
    availablePassengerInitial: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    availablePassengerName: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 2,
    },
    availablePassengerRating: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    availableRatingText: {
        fontSize: 12,
        color: '#6B7280',
        marginLeft: 2,
    },
    rideTimeBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    rideTimeText: {
        fontSize: 11,
        color: '#6B7280',
        marginLeft: 2,
    },
    availableRideDetails: {
        marginBottom: 12,
    },
    availableRideDetailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    availableRideDetailText: {
        fontSize: 13,
        color: '#4B5563',
        marginLeft: 6,
        flex: 1,
    },
    availableRideMeta: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    availableMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    availableMetaText: {
        fontSize: 11,
        color: '#6B7280',
        marginLeft: 2,
    },
    availableRidePrice: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 8,
    },
    availableRidePriceText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    acceptRideButton: {
        width: 80,
    },
    acceptRideButtonGradient: {
        borderRadius: 12,
        paddingVertical: 10,
        paddingHorizontal: 16,
        alignItems: 'center',
    },
    acceptRideButtonText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    quickActionsSection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    quickActionsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    quickActionCard: {
        width: (width - 48) / 2,
        alignItems: 'center',
        marginBottom: 16,
    },
    quickActionIcon: {
        width: 60,
        height: 60,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    quickActionText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#1F2937',
        textAlign: 'center',
    },
    bottomSpacer: {
        height: 80,
    },

    // Rides Tab Styles
    ridesStatsCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 3,
    },
    ridesStatsGrid: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    ridesStatItem: {
        alignItems: 'center',
        flex: 1,
    },
    ridesStatValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    ridesStatLabel: {
        fontSize: 12,
        color: '#6B7280',
    },
    ridesStatDivider: {
        width: 1,
        height: 30,
        backgroundColor: '#E5E7EB',
    },
    historySection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    filterText: {
        fontSize: 14,
        color: '#3B82F6',
        fontWeight: '500',
    },
    historyCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 1,
    },
    historyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    historyPassengerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    historyAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#3B82F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    historyInitial: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFFFFF',
    },
    historyDetails: {
        flex: 1,
    },
    historyPassengerName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    historyDate: {
        fontSize: 12,
        color: '#6B7280',
    },
    historyPrice: {
        alignItems: 'flex-end',
    },
    historyPriceText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#10B981',
    },
    historyRoute: {
        marginBottom: 12,
    },
    historyRoutePoint: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    historyRouteText: {
        fontSize: 14,
        color: '#4B5563',
        marginLeft: 8,
        flex: 1,
    },
    historyFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    historyRating: {
        flexDirection: 'row',
    },
    historyStatus: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
    },
    historyStatusCompleted: {
        backgroundColor: '#D1FAE5',
    },
    historyStatusText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#065F46',
    },

    // Earnings Tab Styles
    earningsOverview: {
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
    },
    earningsOverviewTitle: {
        fontSize: 16,
        color: 'rgba(255, 255, 255, 0.9)',
        marginBottom: 8,
    },
    earningsOverviewAmount: {
        fontSize: 40,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    earningsOverviewSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    periodEarnings: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    periodCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    periodHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    periodTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
    },
    periodAmount: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#10B981',
    },
    periodProgress: {
        height: 6,
        backgroundColor: '#F3F4F6',
        borderRadius: 3,
        overflow: 'hidden',
    },
    periodProgressBar: {
        height: '100%',
        backgroundColor: '#10B981',
        borderRadius: 3,
    },
    earningsStatsSection: {
        marginTop: 24,
        paddingHorizontal: 16,
    },
    earningsStatsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    earningsStatCard: {
        width: (width - 48) / 2,
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    earningsStatValue: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
        marginTop: 8,
        marginBottom: 4,
    },
    earningsStatLabel: {
        fontSize: 12,
        color: '#6B7280',
        textAlign: 'center',
    },
    withdrawalSection: {
        marginTop: 24,
        paddingHorizontal: 16,
        marginBottom: 32,
    },
    withdrawalButton: {
        marginTop: 8,
    },
    withdrawalButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 24,
    },
    withdrawalButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginLeft: 8,
    },
    withdrawalInfo: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginTop: 12,
    },

    // Profile Tab Styles - Main
    profileHeader: {
        paddingTop: 40,
        paddingBottom: 30,
        alignItems: 'center',
    },
    profileAvatarContainer: {
        marginBottom: 16,
    },
    profileAvatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#FFFFFF',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 4,
        borderColor: 'rgba(255, 255, 255, 0.3)',
    },
    profileAvatarImage: {
        borderRadius: 50,
    },
    profileAvatarOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    profileAvatarText: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#1E40AF',
    },
    profileName: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 4,
    },
    profileRating: {
        fontSize: 16,
        color: '#FFFFFF',
        marginBottom: 8,
    },
    profileSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
    },
    vehicleCard: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: -20,
        borderRadius: 16,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    vehicleHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    vehicleTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginLeft: 12,
    },
    vehicleDetails: {
        marginTop: 8,
    },
    vehicleDetailItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    vehicleDetailLabel: {
        fontSize: 14,
        color: '#6B7280',
    },
    vehicleDetailValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
    },
    menuSection: {
        marginTop: 24,
        paddingHorizontal: 16,
        marginBottom: 32,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    menuIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    menuText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#1F2937',
        flex: 1,
    },
    verifiedBadge: {
        backgroundColor: '#D1FAE5',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    verifiedText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#065F46',
    },

    // Profile Sub-tabs common styles
    subTabHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 20,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    backButton: {
        padding: 8,
    },
    subTabTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
    },

    // Mon Profil sub-tab
    profilePhotoSection: {
        padding: 16,
        backgroundColor: '#FFFFFF',
        marginTop: 16,
        marginHorizontal: 16,
        borderRadius: 16,
    },
    profilePhotoContainer: {
        alignItems: 'center',
        marginTop: 8,
    },
    profilePhoto: {
        width: 120,
        height: 120,
        borderRadius: 60,
    },
    profilePhotoPlaceholder: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#F3F4F6',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#E5E7EB',
        borderStyle: 'dashed',
    },
    profilePhotoText: {
        marginTop: 8,
        fontSize: 14,
        color: '#6B7280',
    },
    formSection: {
        padding: 16,
        backgroundColor: '#FFFFFF',
        marginTop: 16,
        marginHorizontal: 16,
        borderRadius: 16,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8,
    },
    textInput: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 12,
        padding: 12,
        fontSize: 16,
        color: '#1F2937',
        backgroundColor: '#F9FAFB',
    },
    saveButton: {
        marginHorizontal: 16,
        marginTop: 24,
        marginBottom: 32,
    },
    saveButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 24,
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginLeft: 8,
    },

    // Documents sub-tab
    documentsStats: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        padding: 20,
        borderRadius: 16,
    },
    documentStat: {
        alignItems: 'center',
        flex: 1,
    },
    documentStatNumber: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    documentStatLabel: {
        fontSize: 12,
        color: '#6B7280',
    },
    documentsList: {
        paddingHorizontal: 16,
        marginTop: 16,
    },
    documentCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    documentHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    documentIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: '#EFF6FF',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    documentInfo: {
        flex: 1,
    },
    documentName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    documentStatus: {
        alignSelf: 'flex-start',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        backgroundColor: '#F3F4F6',
    },
    documentStatusValid: {
        backgroundColor: '#D1FAE5',
    },
    documentStatusPending: {
        backgroundColor: '#FEF3C7',
    },
    documentStatusText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#374151',
    },
    documentDetails: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    documentExpiry: {
        fontSize: 14,
        color: '#6B7280',
    },
    uploadButton: {
        backgroundColor: '#3B82F6',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
    },
    uploadButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
    addDocumentButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderStyle: 'dashed',
    },
    addDocumentText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#3B82F6',
        marginLeft: 8,
    },
    documentsInfo: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: '#FEF3C7',
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 32,
        padding: 16,
        borderRadius: 16,
    },
    documentsInfoText: {
        flex: 1,
        fontSize: 14,
        color: '#92400E',
        marginLeft: 8,
        lineHeight: 20,
    },

    // Aide & Support sub-tab
    helpSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        padding: 20,
        borderRadius: 16,
    },
    faqItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    faqQuestion: {
        fontSize: 16,
        fontWeight: '500',
        color: '#1F2937',
        flex: 1,
    },
    contactSupportSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        padding: 20,
        borderRadius: 16,
    },
    contactMethod: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    contactIcon: {
        width: 48,
        height: 48,
        borderRadius: 24,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    contactInfo: {
        flex: 1,
    },
    contactTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 4,
    },
    contactSubtitle: {
        fontSize: 14,
        color: '#6B7280',
    },
    helpCenterSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 32,
        padding: 20,
        borderRadius: 16,
    },
    helpCenterText: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 16,
        lineHeight: 20,
    },
    helpCenterButton: {
        backgroundColor: '#3B82F6',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        alignItems: 'center',
    },
    helpCenterButtonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 16,
    },

    // Paramètres sub-tab
    settingsSection: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        padding: 20,
        borderRadius: 16,
    },
    settingsSectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 16,
    },
    settingItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    settingLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    settingText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#1F2937',
        marginLeft: 12,
        flex: 1,
    },
    settingRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    settingValue: {
        fontSize: 16,
        color: '#6B7280',
        marginRight: 8,
    },
    resetButton: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 32,
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#EF4444',
        alignItems: 'center',
    },
    resetButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#EF4444',
    },

    // Bottom Navigation
    bottomNavigation: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: Platform.OS === 'android' ? 24 : 8, // Plus d'espace pour la barre Android
        borderTopWidth: 1,
        borderTopColor: '#F3F4F6',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 10,
        height: Platform.OS === 'android' ? 90 : 70, // Plus haut sur Android
    },
    navItem: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        borderRadius: 12,
    },
    navItemActive: {
        backgroundColor: '#EFF6FF',
    },
    navText: {
        fontSize: 11,
        color: '#6B7280',
        marginTop: 4,
    },
    navTextActive: {
        color: '#3B82F6',
        fontWeight: '600',
    },
});